[package]
name = "vga_buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
volatile = { workspace = true }
lazy_static = { workspace = true, features = ["spin_no_std"] }
spin = { workspace = true }